language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: pip install --user -r requirements.txt

addons:
  apt:
    packages:
    - python3-gi

script: python3 EarthPornWallpaper.py
