language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: "pip install -r requirements.txt"

script:
  - python setup_test.py
  - python earthpornwallpaper.py test


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/faf7d279001d2a128c71
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
